### ISSUE TITLE
The website only display 10 blog posts after clicking a tag

### ISSUE THREAD

**Issue by bruce30262** [bamboofox/bamboofox_website#26]
when clicking a tag ( let's say `pwn` ) with more than 10 blog posts  
I was expecting it will display all the blog post that has a `pwn` tag in it  
But in fact it only display 10 blog posts , and exclude the rest of the posts  
Is this a bug or a feature ?  
This might be inconvenient when people try to search the blog post by its tag

**Comment by bananaappletw** [comment]
@bruce30262 
Thanks for the report.
It seems like it's hexo's bug.
https://github.com/hexojs/hexo/issues/1804
Note: keep this issue open here.
If hexo solve this issue we could upgrade hexo to solve this.
